// Generated by CoffeeScript 1.6.2
/*

Using the element of Form in Creative Coding by using Grids. Based on example 2.1.2 in Generative Design. (http://www.generative-gestaltung.de/P_2_1_2_02)
*/


(function() {
  var coffee_draw;

  coffee_draw = function(p5) {
    var myVector;

    myVector = new toxi.geom.Vec2D(window.innerWidth, window.innerHeight).scaleSelf(0.5);
    p5.setup = function() {
      return p5.size($(window).width(), $(window).height());
    };
    return p5.draw = function() {};
  };

  /* do not edit below
  */


  $(window).resize(function() {
    return processing.size($(window).width(), $(window).height());
  });

  $(document).ready(function() {
    var canvas;

    canvas = document.getElementById("p5canvas");
    return window.processing = new Processing(canvas, coffee_draw);
  });

}).call(this);
