// Generated by CoffeeScript 1.6.2
/*

Simple demonstration of 3 modes of drawing, simular to my projection processing code exhibited in Phytodynamica, by James Stone (www.jamesjamesjames.com)
*/


(function() {
  var coffee_draw;

  coffee_draw = function(p5) {
    var circles, drawMode, lines, linesHoriz;

    drawMode = 0;
    circles = function() {
      var circle_size, i, _i, _results;

      p5.noStroke();
      _results = [];
      for (i = _i = 0; _i <= 20; i = _i += 1) {
        circle_size = p5.random(10, 40);
        if (circle_size < 30) {
          p5.fill(255, 0, 0);
        } else {
          p5.fill(0, 0, 255);
        }
        _results.push(p5.ellipse(p5.random(0, p5.width), p5.random(0, p5.height), circle_size, circle_size));
      }
      return _results;
    };
    lines = function() {
      var i, xLoc, _i, _results;

      _results = [];
      for (i = _i = 0; _i <= 10; i = _i += 1) {
        if (p5.random(0, 1) > 0.3) {
          p5.stroke(255, 0, 0);
        } else {
          p5.stroke(0, 0, 255);
        }
        xLoc = p5.random(0, p5.width);
        _results.push(p5.line(xLoc, 0, xLoc, p5.height));
      }
      return _results;
    };
    linesHoriz = function() {
      var i, yLoc, _i, _results;

      _results = [];
      for (i = _i = 0; _i <= 10; i = _i += 1) {
        if (p5.random(0, 1) > 0.3) {
          p5.stroke(255, 0, 0);
        } else {
          p5.stroke(0, 0, 255);
        }
        yLoc = p5.random(0, p5.height);
        _results.push(p5.line(0, yLoc, p5.width, yLoc));
      }
      return _results;
    };
    p5.setup = function() {
      return p5.size($(window).width(), $(window).height());
    };
    return p5.draw = function() {
      switch (drawMode) {
        case 0:
          circles();
          break;
        case 1:
          lines();
          break;
        case 2:
          linesHoriz();
      }
      if (p5.frameCount % 200 === 0) {
        return drawMode = p5.floor(p5.random(0, 3));
      }
    };
  };

  /* do not edit below
  */


  $(window).resize(function() {
    return processing.size($(window).width(), $(window).height());
  });

  $(document).ready(function() {
    var canvas;

    canvas = document.getElementById("p5canvas");
    return window.processing = new Processing(canvas, coffee_draw);
  });

}).call(this);
