// Generated by CoffeeScript 1.3.3
(function() {
  var coffee_draw;

  coffee_draw = function(p5) {
    p5.setup = function() {
      return p5.size($(window).width(), $(window).height());
    };
    return p5.draw = function() {
      var circle_size, i, _i, _results;
      p5.noStroke();
      _results = [];
      for (i = _i = 0; _i <= 200; i = _i += 1) {
        circle_size = p5.random(10, 40);
        if (circle_size < 30) {
          p5.fill(255, 0, 0);
        } else {
          p5.fill(0, 0, 255);
        }
        _results.push(p5.ellipse(p5.random(0, p5.width), p5.random(0, p5.height), circle_size, circle_size));
      }
      return _results;
    };
  };

  /* do not edit below
  */


  $(window).resize(function() {
    return processing.size($(window).width(), $(window).height());
  });

  $(document).ready(function() {
    var canvas;
    canvas = document.getElementById("p5canvas");
    return window.processing = new Processing(canvas, coffee_draw);
  });

}).call(this);
