// Generated by CoffeeScript 1.6.2
(function() {
  var coffee_draw;

  coffee_draw = function(p5) {
    var FlatShape, flatShapes, number_of_shapes, t, t_inc;

    FlatShape = (function() {
      function FlatShape(opts) {
        this.x = opts.x;
        this.y = opts.y;
        this.r = opts.r;
        this.sides = opts.sides;
        this.rotation = opts.rotation;
        this.color = opts.color;
        this.rotValue = 0.0;
      }

      FlatShape.prototype.calc = function() {
        return this.rotValue += this.rotation;
      };

      FlatShape.prototype.drawShape = function(x, y, r, sides) {
        var calcx, calcy, i, theta, theta_inc, _i;

        theta = 0;
        theta_inc = 2 * p5.PI / sides;
        p5.pushMatrix();
        p5.translate(x, y);
        p5.beginShape();
        for (i = _i = 1; _i <= sides; i = _i += 1) {
          p5.rotate(this.rotValue);
          calcx = r * p5.sin(theta);
          calcy = r * p5.cos(theta);
          p5.vertex(calcx, calcy);
          theta += theta_inc;
        }
        p5.endShape(p5.CLOSE);
        return p5.popMatrix();
      };

      FlatShape.prototype.display = function() {
        this.calc();
        p5.fill(this.color);
        p5.noStroke();
        return this.drawShape(this.x, this.y, this.r, this.sides);
      };

      return FlatShape;

    })();
    t = 0.0;
    t_inc = 0.001;
    flatShapes = new Array();
    number_of_shapes = 25;
    p5.setup = function() {
      var i, s, _i, _ref, _results;

      p5.size($(window).width(), $(window).height());
      _results = [];
      for (i = _i = 3, _ref = 3 + number_of_shapes - 1; _i <= _ref; i = _i += 1) {
        s = new FlatShape({
          x: i * p5.width / number_of_shapes,
          y: p5.height / 2,
          r: p5.width / (number_of_shapes * 2),
          sides: 7,
          rotation: p5.random(-0.001, 0.001),
          color: p5.color(p5.random(0, 255))
        });
        _results.push(flatShapes.push(s));
      }
      return _results;
    };
    p5.draw = function() {
      var s, _i, _len, _results;

      p5.background(127);
      p5.scale(0.9);
      p5.rectMode(p5.CENTER);
      p5.translate(-p5.width / number_of_shapes * 2, 0);
      p5.rotate(p5.sin(p5.frameCount / 100) * p5.PI / 12);
      _results = [];
      for (_i = 0, _len = flatShapes.length; _i < _len; _i++) {
        s = flatShapes[_i];
        if (p5.frameCount % 100 === 0) {
          s.rotation = p5.random(-0.01, 0.01);
        }
        _results.push(s.display());
      }
      return _results;
    };
    return p5.mousePressed = function() {
      var s, _i, _len, _results;

      _results = [];
      for (_i = 0, _len = flatShapes.length; _i < _len; _i++) {
        s = flatShapes[_i];
        _results.push(s.color = p5.color(p5.random(0, 255)));
      }
      return _results;
    };
  };

  /* do not edit blow
  */


  $(window).resize(function() {
    return processing.size($(window).width(), $(window).height());
  });

  $(document).ready(function() {
    var canvas;

    canvas = document.getElementById("p5canvas");
    return window.processing = new Processing(canvas, coffee_draw);
  });

}).call(this);
