// Generated by CoffeeScript 1.6.2
(function() {
  var canvas, p5, value;

  canvas = document.getElementById('glibcanvas');

  p5 = new Processing(canvas);

  value = 0;

  p5.setup = function() {
    p5.size(200, 200);
    return p5.noLoop();
  };

  p5.draw = function() {
    p5.noStroke();
    p5.fill(255, 75);
    p5.rect(0, 0, 200, 200);
    p5.stroke(100, 100, 200);
    p5.noFill();
    p5.bezier(0, 100, 33, 100 + value, 66, 100 + value, 100, 100);
    return p5.bezier(100, 100, 133, 100 + -value, 166, 100 + -value, 200, 100);
  };

  p5.mouseMoved = function() {
    value = p5.mouseY - 100;
    return p5.redraw();
  };

  p5.setup();

}).call(this);
