// Generated by CoffeeScript 1.6.2
(function() {
  var coffee_draw;

  coffee_draw = function(p5) {
    p5.setup = function() {
      return p5.size($(window).width(), $(window).height());
    };
    return p5.draw = function() {
      var size;

      p5.rectMode(p5.CENTER);
      size = 200 + p5.sin(p5.frameCount / 100) * 100;
      return p5.rect(p5.width / 2, p5.height / 2, size, size);
    };
  };

  /* zebra ui below
  */


  zebra.ready(function() {
    var root;

    eval(zebra.Import("ui", "layout"));
    root = (new zCanvas("p5canvas")).root;
    root.properties({
      layout: new BorderLayout(8, 8),
      border: new Border(),
      padding: 8,
      kids: {
        TOP: new Button("Top").properties({
          canHaveFocus: false
        }),
        LEFT: new Button("Left").properties({
          canHaveFocus: false
        }),
        RIGHT: new Button("Right").properties({
          canHaveFocus: false
        }),
        BOTTOM: new Button("bottom").properties({
          canHaveFocus: false
        })
      }
    });
    return root.find("//Button")._.add(function() {
      return root.find("//TextField").setValue("");
    });
  });

  /* do not edit below
  */


  /*
  $(window).resize ->
    processing.size $(window).width(), $(window).height()
  */


  $(document).ready(function() {
    var canvas;

    canvas = document.getElementById("p5canvas");
    return window.processing = new Processing(canvas, coffee_draw);
  });

}).call(this);
