// Generated by CoffeeScript 1.6.2
(function() {
  var coffee_draw;

  coffee_draw = function(p5) {
    var backgroundUI;

    backgroundUI = function(bgColor, xOff, yOff) {
      window.context.fillStyle = bgColor;
      return window.context.fillRect(xOff, yOff, p5.width, p5.height);
    };
    p5.setup = function() {
      p5.size($(window).width(), $(window).height());
      return p5.rectMode(p5.CENTER);
    };
    return p5.draw = function() {
      var size;

      backgroundUI("#eee", 0, 60);
      size = 200 + p5.sin(p5.frameCount / 100) * 100;
      p5.noStroke();
      p5.fill(127, 127);
      return p5.rect(p5.width / 2, p5.height / 2, size, size);
    };
  };

  /* zebra ui below
  */


  zebra.ready(function() {
    var myButton;

    eval(zebra.Import("ui", "layout"));
    return window.root = (new zCanvas("p5canvas")).root.properties({
      layout: new BorderLayout(8, 8),
      background: "#eee",
      kids: {
        TOP: new Panel({
          layout: new FlowLayout(CENTER, TOP, HORIZONTAL, 10),
          padding: 10,
          background: "#eee",
          kids: {
            "test1": new Button().properties({
              canHaveFocus: false
            }),
            "test2": new Button("test 2").properties({
              canHaveFocus: false,
              id: "test2"
            }),
            "slider": new Slider(),
            "check": new Checkbox("valueCheck")
          }
        })
      }
    }, myButton = window.root.find("//Button"));
  });

  /*
    create interactions for button presses
    create slider
    have data update slide
  */


  /*
  # alternative style from js
    root.setLayout(newBorderLayout(4,4))
    root.setPadding(4)
    p = new Button("Test")
    # p.setBackground("#00FF00")
    root.add(BOTTOM, p)
  */


  /* do not edit below
  */


  $(window).resize(function() {
    processing.size($(window).width(), $(window).height());
    return window.root.repaint();
  });

  $(document).ready(function() {
    window.canvas = document.getElementById("p5canvas");
    window.processing = new Processing(canvas, coffee_draw);
    return window.context = canvas.getContext('2d');
  });

}).call(this);
